---
deploy_user: app

redmine_domain: opsinfrapath.ru
redmine_port: 3000
redmine_dir: /opt/redmine
redmine_network: redmine

redmine_db_container: redmine-postgres
redmine_db_host: "{{ redmine_db_container }}"
redmine_db_port: 5432
redmine_db_name: redmine
redmine_db_user: redmine
redmine_db_password: "{{ vault_redmine_db_password }}"

redmine_secret_key_base: "{{ vault_redmine_secret_key_base }}"

letsencrypt_webroot: /var/www/letsencrypt

redmine_backends:
  - name: redmine-1
    port: 3001
  - name: redmine-2
    port: 3002
